---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: {{ cookiecutter.driver_name }}
lint:
  name: {{ cookiecutter.lint_name }}
platforms:
  - name: instance-1
provisioner:
  name: {{ cookiecutter.provisioner_name }}
scenario:
  name: ${MOLECULE_SCENARIO_NAME}
verifier:
  name: {{ cookiecutter.verifier_name }}
