---
{% raw -%}
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
    molecule_instance_config: "{{ lookup('env','MOLECULE_INSTANCE_CONFIG') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Destroy molecule instance(s)
      os_server:
        name: "{{ item.name | molecule_instance_with_scenario_name(molecule_yml.scenario.name) }}"
        state: absent
      with_items: "{{ molecule_yml.platforms }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: "# Molecule managed\n\n{{ instance_conf | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
{%- endraw -%}
