---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: {{ cookiecutter.driver_name }}
lint:
  name: {{ cookiecutter.lint_name }}
platforms:
  - name: instance-1
    image: Ubuntu-16.04
    flavor: NO-Nano
provisioner:
  name: {{ cookiecutter.provisioner_name }}
scenario:
  name: {{ cookiecutter.scenario_name }}
verifier:
  name: {{ cookiecutter.verifier_name }}
